export default function getStarterTags(){
	return ["Soccer", "Football", "Hockey", "Baseball", "Basketball", "Video Games", "Cooking", "Traveling", "UCSB", "Computer Science", "Econ", "Bio", "Physics", "Chemistry", "History", "English",
"Reading",
"Eating",
"Writing",
"Pets",
"Dogs",
"Cats",
"Drawing",
"Painting",
"Music",
"Piano",
"Cello",
"Violin",
"Anime",
"Dancing",
"Rap",
"Hip Hop",
"Rock",
"Pop",
"K-pop",
"K-drama",
"sleeping",
"Bowling",
"Baking",
"Fashion",
"Mediation",
"Comedy",
"Origami",
"Livestreaming",
"Cubing",
"Chess",
"Ping Pong",
"Tennis",
"Calligraphy",
"Bread"
]}
